### ISSUE TITLE
"Open API" -> "OpenAPI" and version support

### ISSUE THREAD

**Issue by MikeRalphson** [readmeio/oas#16]
"Open API" in the project description and `README` should be "OpenAPI", and could you please specify which version of OpenAPI document is generated by this tool?

**Comment by gkoberger** [comment]
Fixed! I updated the README, but here's the version info:

  1. This tool can generate Swagger 2 and OAS 3 files
  2. If you use `oas init`, it'll do OAS 3, however you can manually use a Swagger 2 file and it'll work
