### ISSUE TITLE
Remove vulnerabilities that come up when running npm audit

### ISSUE THREAD

**Issue by michaelfarrell76** [readmeio/oas#18]
Running `npm audit` returns 3 vulnerabilities:

- [oas > open](https://www.npmjs.com/advisories/663)
- [oas > swagger-inline > multilang-extract-comments > lodash]( https://npmjs.com/advisories/782)
- [oas > swagger-inline > multilang-extract-comments > lodash](https://npmjs.com/advisories/577  )

I would like to be able to have oas as a dev-dependency, and it is the only dependency I use that has npm audit vulnerabilities.

**Comment by gkoberger** [comment]
Should be fixed in the latest version!

**Comment by michaelfarrell76** [comment]
awesome thanks worked like a charm :)
