### ISSUE TITLE
Are there any plans to support Open API 3.0.0?

### ISSUE THREAD

**Issue by imposibrus** [readmeio/oas#2]
Link issue in readmeio/swagger-inline#8

**Comment by dwasyluk** [comment]
Any updates on this?

**Comment by gkoberger** [comment]
Yes! We were waiting on the package `swagger-parser` to support it, however we'll be switching to `wework/speccy` instead. We hope to have it out soon!

**Comment by gkoberger** [comment]
Support for 3.0 is now live! Post an issue if you run into any bugs :)

**Comment by gkoberger** [comment]
There were some issues with shorthand parameters not supporting OAS 3.0, however that's fixed now!

We now have a full site describing how to use `oas`: http://openap.is/
