### ISSUE TITLE
Remove installation warnings

### ISSUE THREAD

**Issue by michaelfarrell76** [readmeio/oas#20]
I get the following warnings when I install with yarn, the only warnings in our entire monorepo are being emitted by readmeio packages

```
warning oas > base-store > data-store > cache-base > set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
warning oas > base-store > data-store > union-value > set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
```

also see https://github.com/readmeio/rdme/issues/69

**Comment by erunion** [comment]
Tagged to 0.8.17. Thanks for the heads up on this and https://github.com/readmeio/rdme/issues/69

**Comment by michaelfarrell76** [comment]
thanks appreciate the quick response!
