### ISSUE TITLE
How to ignore file types?

### ISSUE THREAD

**Issue by nikmash** [readmeio/oas#347]
I'm experiencing this error:
```Error: Cannot find language definition for 'Dockerfile'```

How can I ignore certain file types?

**Comment by erunion** [comment]
Which command are you running?

**Comment by internationalhouseofdonald** [comment]
I'm having this same error. I'm using:

`oas generate swagger.json`

The error I get is 

`Error: Cannot find language definition for 'clients.txt' at clients.txt`

... where clients.txt is a just a text file filled with strings.

```
Acme Corporation
Soylent Corp
Globex Corporation
Initech
Umbrella Corps
Hooli
Vehement Capital Partners
Massive Dynamic
Boehm-O'Hara
Marks-Braekhus
```

**Comment by internationalhouseofdonald** [comment]
![Screen Shot 2021-03-17 at 6 15 20 PM](https://user-images.githubusercontent.com/20768148/111550769-d3773000-874c-11eb-9e31-da42acffd23b.png)

The docs seem to be incomplete.

**Comment by internationalhouseofdonald** [comment]
My suggestion would be to place the server file in the swagger.json configuration file, and then pass that as a parameter to `swagger-inline`, since right now, this is what is getting passed to the `swaggerInline()` function.


```
globPatterns **/*
providedOptions {
  format: '.json',
  metadata: true,
  scope: undefined,
  base: './swagger.json'
}
```

**Comment by erunion** [comment]
As of v12 it should no longer error out when it can't handle a file it doesn't know how to handle.
