### ISSUE TITLE
oas generate call requires undocumented base filePath

### ISSUE THREAD

**Issue by brianmickel** [readmeio/oas#360]
After running
```
$ npx oas init
This will help you set up an OpenAPI 3.0 Spec (formerly Swagger) in your
repo, so you can start documenting your API!

? Name of the API ExampleName
? Version number 1.0.0
? License ISC
? Full Base URL https://api.example.com/
? Output JSON or YAML file example-api-1.0.0.json
```
Then `npx oas generate`
I get the error:
> Error: No base specification provided!

Finding this "How to provide the `base` parameter for `oas generate`?" #229, explains the call to oas requires an argument like `npx oas generate './example-api-1.0.0.json'`

It would be nice if this was included in both https://openap.is/ and https://github.com/readmeio/oas README
If this is not the correct way to call `oas generate`, then maybe a troubleshooting section could be added

**Comment by mamatela** [comment]
Anything on this? I am getting the same error
