### ISSUE TITLE
Clarify difference between this project and swagger-inline

### ISSUE THREAD

**Issue by sandstrom** [readmeio/oas#539]
Would be neat if your readme (or wiki) had a comparison table between this project and swagger-inline. Pros/cons, where you'd recommend each one, etc.

https://github.com/readmeio/swagger-inline

*see also https://github.com/readmeio/swagger-inline/issues/227*

**Comment by LyingDalai** [comment]
In particular, it would be good to know before compiling if it is possible to use swagger-inline keywords such as `@api` and `@schema`.
