### ISSUE TITLE
[Bug] OAS takes first json instead of swagger.json

### ISSUE THREAD

**Issue by SkeLLLa** [readmeio/oas#6]
Steps 2 reproduce:
* create in some directory several files, e.g. `__agger.json`, `kwagger.json`, `swagger.json`.
* run oas

Actual behaviour:
OAS takes `__agger.json` and tries to do something with it. If it's not swagger, it just fails.

Expected behaviour:
OAS takes additional argument witch points to swagger file location and uses it. If it's not set it looks first for `swagger.base.json`, if not found - for `swagger.json`. If both not found it fails without searching other `*.json` files in directory

**Comment by gkoberger** [comment]
Hey! Currently, the way it works is it transverses all files, and picks the first `.json` or `.yaml` file with an `openapi` or `swagger` attribute.

As of `oas@0.8.8` can now specify the base file via the last argument! So, you can do something like `oas generate swagger.json`, and it will use the provided file. (The documentation previously said you could do this, however now you _actually_ can)

Let me know if you run into issues with it!
