### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'pattern')

### ISSUE THREAD

**Issue by Khauri** [readmeio/oas#616]
Running `oas generate` in version 17.8.0 results in this error:

```sh
/Users/me/prjcts/node_modules/oas/src/cli/lib/utils.js:56
    pattern: info.ops.pattern || null,
                      ^

TypeError: Cannot read properties of undefined (reading 'pattern')
    at Object.exports.findSwagger (/Users/me/prjcts/node_modules/oas/src/cli/lib/utils.js:56:23)
    at module.exports (/Users/me/prjcts/node_modules/oas/src/cli/index.js:31:11)
    at Object.<anonymous> (/Users/me/prjcts/node_modules/oas/bin/oas:8:22)
```

Possibly a typo in [this commit](https://github.com/readmeio/oas/commit/a7dbe6a5b44a2f9ee97e131619c8f98be09f3ceb#diff-a23ee27ba4a6881dac1a68724372fab5cd7717589caec74737315d50eb5a1893R56)?

Should it perhaps be `info.opts.pattern` and not `info.ops.pattern` (misspelled opts?).

oas: 17.8.0
Node: v16.14.0
NPM: 8.5.2

**Comment by erunion** [comment]
Yep, that's my bad. Will get a fix published shortly.

**Comment by erunion** [comment]
Fixed in https://github.com/readmeio/oas/releases/tag/17.8.1
