### ISSUE TITLE
Adding Request Body Nested Object and Array Definitions

### ISSUE THREAD

**Issue by Swhite215** [readmeio/oas#74]
I realize this might not be the correct place to ask this. If you could point me to a better resource that would be appreciated.

How do I describe a request body nested object and/or an array using swagger-inline comments? In the below, the selector portion of the request body is a nested object that looks something like this:
{
      property: {condition: String value},
      property: {condition: Integer value}
}

/*
* @oas [post] /db/{db}/query/document
* description: "Returns information about a specific document."
* parameters:
* - (path) db=test* {String} The name of the database to query.
* - (body) **selector*** {Object} An object containing selectors used for querying
* - (body) fields* {String} An array containing the fields returned by the query
* - (body) limit {Integer:int32} How many documents to return
*/

Using the above returns an empty object for selector. How can I make it return:
{
      selector: {
            property: {condition: String value},
            property: {condition: Integer value}
      },
      fields: ["String1", "String2"],
      limit: 12
}

**Comment by erunion** [comment]
Closing in favor of the other issue you made here: https://github.com/readmeio/swagger-inline/issues/39
