### ISSUE TITLE
Relation with https://openap.is/

### ISSUE THREAD

**Issue by mariomnts** [readmeio/oas#759]
Hey there!

I tried to follow some of the steps listed in https://openap.is/ that involved the tool `oas` and looks like this tool does not do what is documented in there anymore.

Is there a replacement for extracting inline OpenAPI specs from comments?

Thanks!

**Comment by kanadgupta** [comment]
Hi @mariomnts!

The CLI aspect of this tool has been sunset as of [`oas@20`](https://github.com/readmeio/oas/releases/tag/20.0.0). That CLI was a lightweight wrapper around [`swagger-inline`](https://github.com/readmeio/swagger-inline), which is what you're looking for here.

Let us know if you need anything else!

**Comment by kanadgupta** [comment]
Also, the guidance on the openap.is site has some outdated guidance on generating OpenAPI definitions, so we're temporarily redirecting it to [readme.com](https://readme.com) for the time being. We plan on updating our guidance at some point in the near future!

**Comment by mariomnts** [comment]
@kanadgupta what I have just realised is that the docs for shorthand parameters in `swagger-inline` are lost because of the closing of openap.is site
