### ISSUE TITLE
Get Path-level parameters with operation.getParametersAsJSONSchema() and operation.getParameters()

### ISSUE THREAD

**Issue by cosbgn** [readmeio/oas#824]
OpenAPI support common parameters, from their docs:

```
Common Parameters for All Methods of a Path
Parameters shared by all operations of a path can be defined on the path level instead of the operation level. 
Path-level parameters are inherited by all operations of that path. 
A typical use case are the GET/PUT/PATCH/DELETE operations that manipulate a resource accessed via a path parameter. 
```
Currently `operation.getParameters()` returns only operation parameters. Would be ideal if there would be an option like: `mergeWithCommonParameters:true/false` which would also return the common parameters merged with the operation parameters, since they do apply also for this operation.

Is this possible?

**Comment by erunion** [comment]
Which version of `oas` are you using? We've supported common parameters in every accessor that can support common parameters since we added it to `Operation.getParameters()` in https://github.com/readmeio/oas/pull/581. `Operation.getParametersAsJSONSchema` also calls that method internally.

**Comment by cosbgn** [comment]
You are right. I was doing something wrong (filtering only for methods), so common parameters were deleted. It works perfectly. Thanks for having a look.
