### ISSUE TITLE
Import of oas libraries broken

### ISSUE THREAD

**Issue by fellmann** [readmeio/oas#840]
Hi,
I have several issues with the current OAS libraries.

Since @readme/oas-to-snippet 23.0.0 imports are broken.   
`import { SupportedTargets, oasToSnippet } from "@readme/oas-to-snippet";`  
throws  
`This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.ts(2497)`

Yet, in tsconfig.json,  allowSyntheticDefaultImports and esModuleInterop are true.

The import works using @readme/oas-to-snippet 22.1.4, but then calling `oasToSnippet(oas, ...)` does not work anymore:  
`Argument of type 'import("/node_modules/oas/dist/index")' is not assignable to parameter of type 'import("/node_modules/oas/dist/index").default'.ts(2345)
`

What can I do to make it work? Is this a problem with the TS setup, or are the current library releases not compatible with each other?

**Comment by erunion** [comment]
What's the `module` and `moduleResolution` you have configured in your TS config? // @kanadgupta

**Comment by kanadgupta** [comment]
In addition to sending your TS config, mind also sharing your TypeScript and Node versions?

**Comment by kanadgupta** [comment]
I just did a quick test and was able to get this script running with `@readme/oas-to-snippet@24.0.2` and `typescript@5.3.3`:

```ts
import type { SupportedTargets } from "@readme/oas-to-snippet/languages";
import oasToSnippet from "@readme/oas-to-snippet";

const lang: SupportedTargets = "c";

console.log("oasToSnippet:", oasToSnippet);
```

Note that the `SupportedTargets` type import path is `@readme/oas-to-snippet/languages`, not `@readme/oas-to-snippet`.

You'll need to use one of the more recent `module`/`moduleResolution` options (e.g., `NodeNext`/`NodeNext`, `ESNext`/`Bundler`, etc.) and a recent version of TypeScript ([>=4.7, I believe](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-7.html#ecmascript-module-support-in-nodejs)?) 

```json
{
  "compilerOptions": { "module": "NodeNext" }
}
```

**Comment by fellmann** [comment]
Thank you for your investigation. The core problem was `moduleResolution`. Because of an older next.js setup it was set to `node`.

What solved it for me:
- Update typescript to `5.3.3`
- Set `"moduleResolution": "bundler"` (current default for new next.js apps)

Now everything works as expected.
