### ISSUE TITLE
Response model and definition

### ISSUE THREAD

**Issue by hpatoio** [readmeio/oas#9]
I can't find in the example how to describe the format of a response. Seems like `aos` is focuses only on routes.

I wanna add something like this to my definition

```
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Pets"
```
I can't find how to define definition for the response schema and the `Pets` model

**Comment by gkoberger** [comment]
Hey! You can put the definitions in your main `swagger.yaml` (or `.json`) file, and then reference them from the comments.

I can see maybe adding it to comments, too, so you can define your schema closer to wherever you define your models in the code. However, right now, the best way is to include it in your base Swagger/OAS file, just like you would if you weren't using this tool!
